#!python

import logging

from sqlalchemy.orm import Session
from sqlalchemy import select

from src.core import create_db, Base
from src.flashcards import Flashcard
from src.ui import UI


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


engine = create_db()

ui = UI()

with Session(engine) as session:
    fcs = select(Flashcard)
    for x in session.scalars(fcs):
        logger.debug(x)
